SUPERVISOR(VARCHAR COMPANYDIVISION, INT BRANCHNBR,
 VARCHAR BRANCHDESC, VARCHAR SUPERVISOR#);
INCIDENT(INT INCIDENTID, VARCHAR CATEGORY,
 VARCHAR LOCATION, VARCHAR TASK, VARCHAR DESC,
  VARCHAR CAUSES, FLOAT ESTIMATEDLOSS, DATE DATES, TIME TIMES);


CREATE TABLE SUPERVISOR
(
    VARCHAR COMPANYDIVISION,
    INT BRANCHNBR,
    VARCHAR BRANCHDESC,
    VARCHAR LOCATIONS,
    VARCHAR SUPERVISOR#,
    PRIMARY KEY(SUPERVISOR#),
);
CREATE TABLE INCIDENTS
(
    VARCHAR SNUM,
    INT INCIDENTID,
    VARCHAR CATEGORY, 
    VARCHAR TASK, 
    VARCHAR DESCRIPTIONS,
    VARCHAR CAUSES, 
    FLOAT ESTIMATEDLOSS,
    DATE DATES, 
    TIME TIME,
    PRIMARY KEY(INCIDENTID),
    FOREIGN KEY (SNUM) REFERENCES SUPERVISOR(SUPERVISOR#),
);